### ISSUE TITLE
Bit Vector not generated for a few APKs : trial run1 

### ISSUE THREAD

**Issue by amehrotra91** [twinklegupta/CS230-Project#13]

**Comment by swati3124** [comment]
The issue is with the parser. It is not able to detect or parse activities to write in AndroidManifest.xml file -> incorrect manifest file -> results in null opcode -> results in null feature vector

Incorrect manifest files attached for reference. Closing the issue.

[Archive.zip](https://github.com/twinklegupta/CS230-Project/files/1045861/Archive.zip)
